*NIX:
	make libs
	make

Visual Studio 2019:
	[One time, from within Zaimoni.STL/Pure.C; sets up compiler detection headers]
	nmake -f NMakefile
	[after above]
	Cataclysm.sln

MSys MingWin *should* use the *NIX instructions unaltered (not tested).

Makefile.Windows is for building with MingWin from the Windows CMD shell, with make.